
#  Run with: source .env; docker-compose run --service-ports photodisplay bash
# (service-ports will open the ports as designated here.)
# source python_dock/.env; docker-compose -f python_dock/docker-compose.yaml run --service-ports photodisplay

# export /home/pi/photoDisplayer=/home/lewis/gitRepos/photoDisplayer/; docker-compose -f \ 
# ~/gitRepos/photoDisplayer/docker/python_dock/docker-compose.yaml run --service-ports photodisplay bash

version: '2'
# /home/pi/photoDisplayer="/home/lewis/gitRepos/photoDisplayer/"
services:
  photodisplay:
    # build: .
    image: photodisplay2
    # restart: always
  #      ports:
    ports:
      - "80:80"     # The HTTP port
      # - "8080:8080" # The Web UI (enabled by --api)
      # - "443:443"
    # command:
    #   /bin/bash
    stdin_open: true
    tty: true
    volumes:
      # Mount the code
      - /home/pi/photoDisplayer:/app
      # Mount the photos
      - /mnt/photos:/photos
      # Mount X11 forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Mount timezone files
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro 
      # Mount the directory for the site
      - /home/pi/photoDisplayer/site:/var/www/html
      # Databases
      - /home/pi/photoDisplayer/databases:/var/www/databases
      # Configuration xml file
      - /home/pi/photoDisplayer/config:/var/www/config
    environment:
      - XAUTHORITY=$XAUTHORITY
      - DISPLAY=$DISPLAY
    devices: 
      - /dev/vchiq:/dev/vchiq
    privileged: true
#  docker run -it -v /home/lewis/gitRepos/photoDisplayer/:/usr/src/app -w /usr/src/app photodisplay python pyInit/addPics.py

 #  -e XAUTHORITY=$XAUTHORITY 
 # # docker run -ti --rm -v /home/lewis/gitRepos/photoDisplayer:/app
 #  # -v /home/lewis/tmp_exp:/tmp 
 #  # -v /tmp/.X11-unix:/tmp/.X11-unix
 #  # -v /etc/timezone:/etc/timezone:ro
 #  # -v /etc/localtime:/etc/localtime:ro 
 #  -e DISPLAY=$DISPLAY photodisplay bash
