
#  Run with: source .env; docker-compose run --service-ports photodisplay bash
# (service-ports will open the ports as designated here.)
# source python_dock/.env; docker-compose -f python_dock/docker-compose.yaml run --service-ports photodisplay

# export /home/pi/photoDisplayer=/home/lewis/gitRepos/photoDisplayer/; docker-compose -f \ 
# ~/gitRepos/photoDisplayer/docker/python_dock/docker-compose.yaml run --service-ports photodisplay bash

version: '2'
# /home/pi/photoDisplayer="/home/lewis/gitRepos/photoDisplayer/"
services:

  display_frontend:
    build: 
      dockerfile: frontendDocker
      context: .
#    image: photodisplay
    # restart: always
    ports:
      - "80:80"     # The HTTP port
    command:
      - /bin/bash -c "python /app/display/displayServer.py > /dev/null & && python /app/display/screenPowerServer.py > /dev/null & "
    stdin_open: true
#    tty: true
    volumes:
      # Mount the code
      - /home/pi/photoDisplayer:/app
      # Mount the photos
      - /mnt/photos:/photos
      # Mount database
      - /mnt/server_appdata/photoDisplayer/databases:/app/databases
      # Mount X11 forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /home/pi/.Xauthority:/root/.Xauthority:rw
      # Mount timezone files
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro 
      # Mount the directory for the site
      - /home/pi/photoDisplayer/site:/var/www/html
      # Databases
      - /home/pi/photoDisplayer/databases/savedSlideshows.db:/var/www/html/savedSlideshows.db
      - /home/pi/photoDisplayer/databases/savedSlideshows.db:/app/databases/savedSlideshows.db
#       - /home/pi/photoDisplayer/databases:/var/www/databases
      # Configuration xml file
      - /home/pi/photoDisplayer/config:/var/www/config
    environment:
      - XAUTHORITY=/root/.Xauthority
      - DISPLAY=$DISPLAY
    devices: 
      - /dev/vchiq:/dev/vchiq
    privileged: true
    network_mode: host
    #    hostname: raspberrypi
#  docker run -it -v /home/lewis/gitRepos/photoDisplayer/:/usr/src/app -w /usr/src/app photodisplay python pyInit/addPics.py

